---
name: test
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Install the site-generator
        run: pip install -r requirements.txt
      - name: Build the site.
        run: aip-site-gen . /out
